export const BWS_UPSTREAM_MODE_ENV = 'BWS_UPSTREAM_MODE';
export const BWS_UPSTREAM_EXPORT_SELECTION_PATH_ENV = 'BWS_UPSTREAM_EXPORT_SELECTION_PATH';
export const BWS_UPSTREAM_API_BASE_URL_ENV = 'BWS_UPSTREAM_API_BASE_URL';
export const BWS_UPSTREAM_API_TIMEOUT_MS_ENV = 'BWS_UPSTREAM_API_TIMEOUT_MS';
