import { accepted, blocked, type BoundaryResult, type BettingWinReference } from './local-types.js';

const MANIFEST_HASH_REGEX = /^[0-9a-f]{64}$/;

export interface BettingWinContractBundleMetadata {
  readonly packageName: string;
  readonly version: string;
  readonly schemaVersion: string;
  readonly manifestHash: string;
  readonly generatedBy: 'betting-win';
}

export const CONTRACT_IMPORT_STATUS = 'blocked_until_pinned_betting_win_export' as const;

export function toBettingWinReference(metadata: unknown): BoundaryResult<BettingWinReference> {
  if (!isRecord(metadata)) {
    return blocked(
      'CONTRACT_METADATA_INVALID',
      'The contract bundle metadata must be an object.',
      'Pinned betting-win contract/export package metadata.',
    );
  }

  const packageName = readRequiredString(metadata, 'packageName', 'CONTRACT_PACKAGE_NAME_INVALID', 'The contract bundle package name must be a non-empty canonical string.');
  if (!packageName.ok) {
    return packageName;
  }
  const version = readRequiredString(metadata, 'version', 'CONTRACT_VERSION_INVALID', 'The contract bundle version must be a non-empty canonical string.');
  if (!version.ok) {
    return version;
  }
  const schemaVersion = readRequiredString(metadata, 'schemaVersion', 'CONTRACT_SCHEMA_VERSION_INVALID', 'The contract bundle schema version must be a non-empty canonical string.');
  if (!schemaVersion.ok) {
    return schemaVersion;
  }

  if (metadata.generatedBy !== 'betting-win') {
    return blocked('CONTRACT_SOURCE_NOT_BETTING_WIN', 'The contract bundle must be generated by betting-win.', 'Pinned betting-win contract/export package metadata.');
  }
  if (typeof metadata.manifestHash !== 'string' || !MANIFEST_HASH_REGEX.test(metadata.manifestHash)) {
    return blocked('CONTRACT_MANIFEST_HASH_INVALID', 'The contract bundle must include a canonical lower-case 64-hex manifest hash.', 'Export manifest hash from betting-win.');
  }
  return accepted({
    source: 'betting-win',
    contractVersion: `${packageName.value}@${version.value}:${schemaVersion.value}`,
    manifestHash: metadata.manifestHash,
  });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function readRequiredString(
  metadata: Record<string, unknown>,
  fieldName: keyof BettingWinContractBundleMetadata,
  code: string,
  message: string,
): BoundaryResult<string> {
  const value = metadata[fieldName];
  if (typeof value !== 'string' || value.length === 0 || value !== value.trim()) {
    return blocked(code, message, 'Pinned betting-win contract/export package metadata.');
  }
  return accepted(value);
}
