import { accepted, blocked, type BoundaryResult, type BettingWinReference } from './local-types.js';

export interface BettingWinContractBundleMetadata {
  readonly packageName: string;
  readonly version: string;
  readonly schemaVersion: string;
  readonly manifestHash: string;
  readonly generatedBy: 'betting-win';
}

export const CONTRACT_IMPORT_STATUS = 'blocked_until_pinned_betting_win_export' as const;

export function toBettingWinReference(metadata: BettingWinContractBundleMetadata): BoundaryResult<BettingWinReference> {
  if (metadata.generatedBy !== 'betting-win') {
    return blocked('CONTRACT_SOURCE_NOT_BETTING_WIN', 'The contract bundle must be generated by betting-win.', 'Pinned betting-win contract/export package metadata.');
  }
  if (metadata.manifestHash.trim().length < 32) {
    return blocked('MISSING_MANIFEST_HASH', 'The contract bundle must include a stable manifest hash.', 'Export manifest hash from betting-win.');
  }
  return accepted({
    source: 'betting-win',
    contractVersion: `${metadata.packageName}@${metadata.version}:${metadata.schemaVersion}`,
    manifestHash: metadata.manifestHash,
  });
}
