from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SHELL_FILES = [
    'zip_codebase.sh', 'pull_artifacts_and_zip_codebase.sh', 'update_git.sh',
    'check_progress.sh', 'watch_progress.sh', 'open_log.sh', 'start.sh', 'stop.sh',
    'run-autonomous-implementation.sh', 'run-paper-evaluation.sh', 'run-paper-autopilot.sh', 'run-autonomous-bugfix.sh', 'run-bugfix-autopilot.sh',
    'automation.config.sh', '.automation/lib/run_common.sh', '.automation/lib/controller_hardening_v2.sh', '.automation/lib/telegram_notify.sh',
]

REQUIRED_FRAGMENTS = {
    'update_git.sh': [
        'git pull --ff-only --autostash',
        'GIT_ASKPASS',
        'clear_local_extraheaders_quietly',
        'detached HEAD is not supported',
        'refusing to commit secret-like path',
        'stage_required_executable_modes()',
        'tools/required_executable_paths.js',
        'git update-index --chmod=+x',
    ],
    'zip_codebase.sh': [
        '--artifacts-only',
        'created_zip=%s',
        'file_count=%s',
        'sha256=%s',
        'zip -q -1 -r "$tmp_zip" artifacts',
        'zip -q -1 -@ "$tmp_zip" < "$list_file"',
        '.zip-codebase-list.tmp.XXXXXXXXXX',
        '/runtime/*',
    ],
    'pull_artifacts_and_zip_codebase.sh': [
        'REMOTE_ARTIFACT',
        'sshpass',
        'REMOTE_REPO basename mismatch',
        '"$LOCAL_ROOT/zip_codebase.sh"',
        '--remote-codebase',
        'No automation.config.sh',
    ],
    'check_progress.sh': [
        'autonomous_implementation_*',
        'autonomous_bugfix_*',
        'paper_evaluation_*',
        'bugfix_autopilot_*',
        'campaign_coverage.tsv',
        'final-summary.md',
        'cycles/cycle_',
    ],
    'watch_progress.sh': [
        '--once',
        '--fast',
        '--base-url',
        'progress_source=local_artifacts_no_service',
    ],
    'open_log.sh': [
        '--controller',
        '--codex',
        '--paper',
        '--bugfix',
        '--cycle',
        'cycles/cycle_',
        'bugfix_autopilot_*',
        'round_*',
    ],
    'start.sh': [
        'Node is missing. Activate the repo runtime first',
        'nvm use',
        'node scripts/restore-required-executable-bits.js',
        'npm run validate',
    ],
    'stop.sh': [
        'has no long-running service',
        'No provider, trading, database, worker, scheduler, or production process was stopped.',
    ],
    '.automation/lib/telegram_notify.sh': [
        'telegram_notify_send_final()',
        'telegram_notify_build_final_message()',
        'telegram_notify_message_version()',
        '20260712.pretty_v5_parent_lock_actions',
        "parse_mode: 'HTML'",
        'TELEGRAM_NOTIFY_DRY_RUN',
        'TELEGRAM_NOTIFY',
        'TELEGRAM_BOT_TOKEN',
        'TELEGRAM_CHAT_ID',
        'telegram_notification=skipped missing_config',
        'BUGFIX_AUTOPILOT_COMPLETE',
        'BUGFIX_AUTOPILOT_BUDGET_EXHAUSTED',
        'BUGFIX_AUTOPILOT_BLOCKED_HANDOFF_MISMATCH',
        'BUGFIX_AUTOPILOT_BLOCKED_LOCK_RELEASE',
        'PAPER_AUTOPILOT_BLOCKED_IMPLEMENTATION_PARTIAL_SOURCE_CHANGE',
        'PAPER_AUTOPILOT_BLOCKED_CHILD_IDENTITY',
        'PAPER_AUTOPILOT_BLOCKED_LOCK_RELEASE',
        'PAPER_EVALUATION_BLOCKED_LOCK_RELEASE',
        'PAPER_AUTOPILOT_PINNED_BUNDLE_ACCEPTED_PRIVATE_REPORT_WRITTEN',
    ],
    '.automation/lib/controller_hardening_v2.sh': [
        'automation_v2_claim_env_file_atomic()',
        'automation_v2_validate_parent_lock_loaded()',
        'automation_v2_load_parent_lock_owned()',
        'automation_v2_parent_lock_mtime_epoch()',
        'automation_v2_touch_owned_parent_lock()',
        'automation_v2_release_owned_parent_lock()',
        'automation_v2_process_state()',
        'automation_v2_process_alive()',
        'automation_v2_wait_for_pid_exit()',
        'automation_v2_publish_child_result()',
        'automation_v2_validate_child_result_file()',
        'verified process remains alive after TERM and KILL',
        'HEARTBEAT_SOURCE',
        'file_mtime',
        'zip -q -1 -r',
    ],
    '.automation/lib/run_common.sh': [
        'automation_acquire_lock()',
        'automation_claim_lock_file()',
        'automation_emit_lock_file()',
        'lock was acquired concurrently',
        'automation_force_unlock()',
        'automation_build_artifacts_zip()',
        'automation_refresh_final_artifacts_zip()',
        'automation_v2_zip_with_timeout "$timeout_seconds" "$tmp" "$root" "${entries[@]}"',
        'zip -q -1 -r "$zip_tmp" artifacts',
        'automation_run_validations()',
        'automation_require_cycle_artifacts()',
        'automation_read_continue_status()',
        'automation_run_argv_command()',
        'automation_source_tree_fingerprint()',
        'automation_source_path_is_excluded()',
        'automation_assert_no_incompatible_locks()',
        'automation_run_managed_argv()',
        'automation_terminate_process_group()',
        'active_child_pid=',
        'kill -TERM',
        'missing continue status file',
        'unknown continue status',
    ],
    'run-autonomous-implementation.sh': [
        'automation_v2_publish_child_result',
        'publish_parent_child_result()',
        'artifacts_zip_scope=full_artifacts_directory',
        'final_artifacts_zip_refresh=post_lock_release_atomic',
        'automation_refresh_final_artifacts_zip "$ZIP_TIMEOUT_SECONDS" "$AUTOMATION_REPO_ROOT" "$AUTOMATION_RUN_DIR"',
        'automation_v2_zip_with_timeout "$ZIP_TIMEOUT_SECONDS" "$tmp" "$AUTOMATION_REPO_ROOT" "artifacts"',
        '--model MODEL',
        '--fallback-model MODEL',
        '--repo-dir PATH',
        '--cycle-timeout VALUE',
        '--validation-timeout VALUE',
        '--install-timeout VALUE',
        '--zip-timeout VALUE',
        '--max-cycles N',
        '--sandbox MODE',
        '--auto-install',
        '--allow-parallel',
        '--handover-paper-mode',
        '--handover-bugfix-audit',
        '--print-config',
        '--stream',
        '--no-stream',
        'No --task flag is supported',
        'docs/automation/current-implementation-task.md',
        'telegram_notify_send_final "run-autonomous-implementation.sh"',
        'automation_require_cycle_artifacts',
        'automation_read_continue_status',
        'check_only_validation_failed',
        'AUTONOMOUS_GOAL_COMPLETE=yes',
        'BLOCKED=yes',
        'exit 3',
        'Activate the repo runtime in the parent shell first',
        'never sources nvm.sh',
        'baseline_validation=enabled',
        'strict_handoff_parser=enabled',
        'strict_schema_v1_key_allowlists=enabled',
        'source_evidence_sha256_verification=enabled',
        'source_fingerprint_reconciliation=enabled',
        'input_handoff_immutable=enabled',
        'machine_readable_final_stdout=enabled',
        'lock_acquisition_before_run_dir=enabled',
        'lock_release_failure_classification=enabled',
        'lock_preservation_on_release_failure=enabled',
        'lock_release_failed_lock_preserved',
        "printf 'lock_release_status=%s\\n'",
        "printf 'lock_preserved=%s\\n'",
        'write_consumed_handoff_marker',
        'remove_consumed_handoff_marker',
    ],
    'run-autonomous-bugfix.sh': [
        'automation_v2_publish_child_result',
        'publish_parent_child_result()',
        'artifacts_zip_scope=full_artifacts_directory',
        'final_artifacts_zip_refresh=post_lock_release_atomic',
        'automation_refresh_final_artifacts_zip "$ZIP_TIMEOUT_SECONDS" "$AUTOMATION_REPO_ROOT" "$AUTOMATION_RUN_DIR"',
        'automation_v2_zip_with_timeout "$ZIP_TIMEOUT_SECONDS" "$tmp" "$AUTOMATION_REPO_ROOT" "artifacts"',
        '--from-artifacts PATH',
        '--bugfix-focus-file PATH',
        '--campaign-area SLUG',
        '--model MODEL',
        '--fallback-model MODEL',
        '--repo-dir PATH',
        '--cycle-timeout VALUE',
        '--validation-timeout VALUE',
        '--handover-autonomous-implementation',
        '--no-context-retry',
        '--print-config',
        'Read-only source bug-audit and strict implementation-handoff controller',
        'It must not patch app source directly',
        'BUGFIX_AUDIT_COMPLETE=yes',
        'CONTINUE_REQUIRED=yes',
        'HANDOVER_AUTONOMOUS_IMPLEMENTATION=yes',
        'BLOCKED=yes',
        'request_flags.txt',
        'HANDOVER_AUTONOMOUS_IMPLEMENTATION_REQUIRED',
        'CAMPAIGN_AREA_COMPLETE',
        'SOURCE_EVIDENCE_COMPLETE',
        'BUG_IDS',
        'IMPLEMENTATION_SCOPE',
        'HANDOVER_SCHEMA_VERSION=1',
        'HANDOFF_FINGERPRINT',
        'automation_v2_add_or_verify_fingerprint',
        'BUG_SIGNATURE',
        'source_status_snapshot',
        'artifact_hint_resolved_before_run_dir=yes',
        'automation_v2_source_tree_fingerprint',
        'source_mutation_detected=yes',
        'bugfix_check_only_source_mutation_detected',
        'context_window',
        'model_availability',
        "printf 'run_dir=%s\\n'",
        "printf 'final_status=%s\\n'",
        'write_implementation_handoff',
        'autonomous-implementation-handover.env',
        'telegram_notify_send_final "$SCRIPT_NAME"',
        'automation_require_cycle_artifacts',
        'exit 3',
        'Activate the repo runtime in the parent shell first',
        'never sources nvm.sh',
        'lock_acquisition_before_run_dir=enabled',
        'lock_release_failure_classification=enabled',
        'lock_preservation_on_release_failure=enabled',
        'lock_release_failed_lock_preserved',
        'unexpected_controller_exit',
        "printf 'lock_release_status=%s\\n'",
        "printf 'lock_preserved=%s\\n'",
    ],
    'run-paper-evaluation.sh': [
        'automation_v2_publish_child_result',
        'publish_parent_child_result()',
        'artifacts_zip_scope=full_artifacts_directory',
        'final_artifacts_zip_refresh=post_lock_release_atomic',
        'automation_refresh_final_artifacts_zip "$ZIP_TIMEOUT_SECONDS" "$AUTOMATION_REPO_ROOT" "$AUTOMATION_RUN_DIR"',
        'automation_v2_zip_with_timeout "$ZIP_TIMEOUT_SECONDS" "$tmp" "$AUTOMATION_REPO_ROOT" "artifacts"',
        'Default duration: 72h.',
        '--adaptive',
        '--keep-monitoring-when-ready',
        '--model MODEL',
        '--fallback-model MODEL',
        '--repo-dir PATH',
        '--check-only',
        '--codex-phase-timeout VALUE',
        '--validation-timeout VALUE',
        '--zip-timeout VALUE',
        'SUREBET_PINNED_BUNDLE',
        'SUREBET_REQUIRE_PINNED_BUNDLE',
        'SUREBET_REQUIRE_PINNED_BUNDLE must be unset, 0, or 1',
        'validate_pinned_bundle_preflight()',
        'automation_run_argv_command',
        'controller_mode=single_pass_no_service',
        'duration_semantics=maximum_controller_budget_not_monitoring_runtime',
        'interval_semantics=workflow_compatibility_no_wait_in_single_pass_mode',
        'verify_paper_read_only_state()',
        'PAPER_EVALUATION_BLOCKED_SOURCE_MUTATION',
        "printf 'run_dir=%s\\n'",
        "printf 'final_status=%s\\n'",
        "printf 'paper_result=%s\\n'",
        'paper_service_lifecycle=none',
        'PAPER_EVALUATION_READY_PRIVATE_FIXTURE_ONLY_BLOCKED_ON_PINNED_BUNDLE',
        'PAPER_EVALUATION_PINNED_BUNDLE_ACCEPTED_PRIVATE_REPORT_WRITTEN',
        'PAPER_EVALUATION_BLOCKED_INVALID_PINNED_BUNDLE',
        'paper-mode-to-autonomous-implementation.env',
        'HANDOVER_SCHEMA_VERSION=1',
        'SOURCE_EVIDENCE_SHA256',
        'automation_v2_add_or_verify_fingerprint',
        'automation_v2_write_env_atomic',
        'canonical_paper_handoff_schema=1',
        'atomic_paper_handoff=enabled',
        'bounded_artifacts_zip=enabled',
        'atomic_standalone_lock_acquisition=enabled',
        'lock_acquisition_before_run_dir=enabled',
        'lock_release_failure_classification=enabled',
        'lock_preservation_on_release_failure=enabled',
        'PAPER_EVALUATION_BLOCKED_LOCK_RELEASE',
        "printf 'lock_release_status=%s\\n'",
        "printf 'lock_preserved=%s\\n'",
        'telegram_notify_send_final "run-paper-evaluation.sh"',
        'automation_v2_zip_with_timeout',
        'Activate the repo runtime in the parent shell first',
        'Does not source nvm.sh',
        'local rc=$?',
    ],

    'run-bugfix-autopilot.sh': [
        'artifacts_zip_scope=full_artifacts_directory',
        'final_artifacts_zip_refresh=post_lock_release_atomic',
        'automation_refresh_final_artifacts_zip "$ZIP_TIMEOUT_SECONDS" "$AUTOMATION_REPO_ROOT" "$AUTOMATION_RUN_DIR"',
        'automation_v2_zip_with_timeout "$ZIP_TIMEOUT_SECONDS" "$tmp" "$AUTOMATION_REPO_ROOT" "artifacts"',
        'Parent bug-audit -> implementation -> same-area re-audit supervisor',
        '--bugfix-duration VALUE',
        '--implementation-duration VALUE',
        '--max-rounds N',
        '--max-same-handoff N',
        '--bugfix-max-cycles N',
        '--implementation-max-cycles N',
        '--bugfix-codex-timeout VALUE',
        '--implementation-cycle-timeout VALUE',
        'controller_mode=bug_audit_implementation_same_area_reaudit_parent',
        'campaign_coverage.tsv',
        'boundary_and_input_contracts',
        'cross_area_regression_and_campaign_closure',
        'run-autonomous-bugfix.sh',
        'run-autonomous-implementation.sh',
        '--handover-bugfix-audit',
        'mandatory_same_area_reaudit=enabled',
        'child_aware_lock=enabled',
        'cross_controller_lock_guard=enabled',
        'atomic_parent_lock_acquisition=enabled',
        'parent_lock_mtime_heartbeat=enabled',
        'parent_child_cleanup_failure_classification=enabled',
        'parent_lock_release_failure_classification=enabled',
        'lock_preservation_on_child_identity_failure=enabled',
        'verified_force_unlock_termination=enabled',
        'child_telegram_notifications=suppressed_by_parent',
        'parent_telegram_notification=final_only',
        '"TELEGRAM_NOTIFY=0"',
        'automation_assert_no_incompatible_locks',
        'automation_v2_claim_env_file_atomic',
        'automation_v2_touch_owned_parent_lock',
        'refresh_parent_lock_heartbeat',
        'BUGFIX_AUTOPILOT_COMPLETE',
        'BUGFIX_AUTOPILOT_BLOCKED_AUDIT_CHILD',
        'BUGFIX_AUTOPILOT_BLOCKED_IMPLEMENTATION_CHILD',
        'BUGFIX_AUTOPILOT_BLOCKED_IMPLEMENTATION_NOOP',
        'BUGFIX_AUTOPILOT_BLOCKED_HANDOFF_MISMATCH',
        'BUGFIX_AUTOPILOT_BLOCKED_REPEATED_HANDOFF',
        'BUGFIX_AUTOPILOT_BLOCKED_CHILD_IDENTITY',
        'BUGFIX_AUTOPILOT_BLOCKED_LOCK_RELEASE',
        'BUGFIX_AUTOPILOT_BLOCKED_CHILD_RESULT',
        'child_terminal_result_transport=atomic_side_channel_v1',
        'child_stdout_machine_parsing=disabled',
        'AUTOMATION_CHILD_RESULT_FILE=$terminal_result',
        'automation_v2_validate_child_result_file',
        'BUGFIX_AUTOPILOT_BUDGET_EXHAUSTED',
        'HANDOVER_FINGERPRINT',
        'LAST_CHILD_SOURCE_CHANGED',
        'AUDIT_SOURCE_FINGERPRINT',
        'bugfix_child_mutated_source',
        "printf 'child_cleanup_status=%s\\n'",
        "printf 'lock_release_status=%s\\n'",
        "printf 'lock_preserved=%s\\n'",
        'telegram_notify_send_final "$SCRIPT_NAME"',
        'paper_controller_calls=prohibited',
        'service_lifecycle=none',
        'never sources nvm.sh',
    ],
    'run-paper-autopilot.sh': [
        'artifacts_zip_scope=full_artifacts_directory',
        'final_artifacts_zip_refresh=post_lock_release_atomic',
        'automation_refresh_final_artifacts_zip "$ZIP_TIMEOUT_SECONDS" "$AUTOMATION_REPO_ROOT" "$AUTOMATION_RUN_DIR"',
        'automation_v2_zip_with_timeout "$ZIP_TIMEOUT_SECONDS" "$tmp" "$AUTOMATION_REPO_ROOT" "artifacts"',
        'Parent no-service paper/autonomous supervisor for betting-win-surebet',
        '--paper-duration VALUE',
        '--implementation-duration VALUE',
        '--max-same-handoff N',
        '--paper-codex-timeout VALUE',
        '--implementation-cycle-timeout VALUE',
        'paper_autopilot',
        'run-paper-evaluation.sh',
        'run-autonomous-implementation.sh',
        'PAPER_AUTOPILOT_BLOCKED_ON_PINNED_BUNDLE',
        'PAPER_AUTOPILOT_BLOCKED_IMPLEMENTATION_NOOP',
        'PRIVATE_PAPER_REEVALUATION_REQUIRED',
        'canonical_paper_handoff_required=enabled',
        'legacy_paper_handoff_normalization=disabled',
        'validate_paper_handoff()',
        'SOURCE_EVIDENCE_SHA256',
        'cross_controller_lock_guard=enabled',
        'atomic_parent_lock_acquisition=enabled',
        'parent_lock_mtime_heartbeat=enabled',
        'verified_force_unlock_termination=enabled',
        'automation_v2_claim_env_file_atomic',
        'automation_v2_touch_owned_parent_lock',
        'parent_child_cleanup_failure_classification=enabled',
        'parent_lock_release_failure_classification=enabled',
        'lock_preservation_on_child_identity_failure=enabled',
        'child_telegram_notifications=suppressed_by_parent',
        'parent_telegram_notification=final_only',
        '"TELEGRAM_NOTIFY=0"',
        'PAPER_AUTOPILOT_BLOCKED_CHILD_IDENTITY',
        'PAPER_AUTOPILOT_BLOCKED_CHILD_RESULT',
        'child_terminal_result_transport=atomic_side_channel_v1',
        'child_stdout_machine_parsing=disabled',
        'AUTOMATION_CHILD_RESULT_FILE=$terminal_result',
        'automation_v2_validate_child_result_file',
        'PAPER_AUTOPILOT_BLOCKED_LOCK_RELEASE',
        "printf 'lock_release_status=%s\\n'",
        '--zip-timeout "$ZIP_TIMEOUT_SECONDS"',
        'paper_service_lifecycle=none',
        'telegram_notify_send_final "run-paper-autopilot.sh"',
        'never sources nvm.sh',
    ],
    'automation.config.sh': [
        'AUTOMATION_CONFIG_READY=1',
        'AUTOMATION_REPO_NAME="betting-win-surebet"',
        '.automation/lib/controller_hardening_v2.sh',
        '.automation/lib/telegram_notify.sh',
        'AUTOMATION_MAX_CODEX_FAILURES',
        'AUTOMATION_MAX_CONSECUTIVE_VALIDATION_FAILURES',
        'AUTOMATION_INSTALL_TIMEOUT',
        'AUTOMATION_ZIP_TIMEOUT',
        'run-paper-evaluation.sh is surebet-specific: no service lifecycle, private fixture/pinned-bundle only.',
        'PAPER_SUPPORTED="${PAPER_SUPPORTED:-1}"',
        'SUREBET_REQUIRE_PINNED_BUNDLE',
        'AUTOMATION_PAPER_AUTOPILOT_COMMAND',
        'AUTOMATION_PAPER_COMMAND="$AUTOMATION_PAPER_AUTOPILOT_COMMAND"',
        'AUTOMATION_BUGFIX_AUTOPILOT_COMMAND',
        'AUTOMATION_BUGFIX_COMMAND="$AUTOMATION_BUGFIX_AUTOPILOT_COMMAND"',
        'run-bugfix-autopilot.sh',
    ],
    'docs/automation/README.md': [
        'Repo automation contract: betting-win-surebet',
        './zip_codebase.sh --artifacts-only',
        'git pull --ff-only --autostash',
        '.automation/lib/telegram_notify.sh',
        'Root `run-*` controllers',
        'run-autonomous-implementation.sh',
        'run-autonomous-bugfix.sh',
        'run-paper-autopilot.sh',
        'run-bugfix-autopilot.sh',
        'TELEGRAM_NOTIFY=0',
        'one final campaign message',
        'atomic child-result side channel',
        'complete `artifacts/` directory',
        'writable `/tmp`',
        'REMOTE_REPO` basename',
    ],
    'docs/automation/autonomous-implementation.md': [
        '--model cli-default',
        '--fallback-model none',
        '--cycle-timeout',
        '--validation-timeout',
        '--handover-paper-mode',
        'check-only must fail',
        'Telegram',
        'AUTONOMOUS_GOAL_COMPLETE=yes',
        'BWS_FULL_PLATFORM_IMPLEMENTATION_V1',
    ],
    'docs/automation/autonomous-bugfix.md': [
        'read-only audit and strict implementation-handoff controller',
        '--handover-autonomous-implementation',
        '--bugfix-focus-file PATH',
        '--campaign-area SLUG',
        'autonomous-implementation-handover.env',
        'must not patch app source directly',
        'BUGFIX_AUDIT_COMPLETE=yes',
        'HANDOVER_AUTONOMOUS_IMPLEMENTATION=yes',
        'request_flags.txt',
        'content fingerprints',
        'already-dirty',
        'before the current run directory is created',
    ],
    'docs/automation/bugfix-autopilot.md': [
        'run-bugfix-autopilot.sh',
        'audit -> implementation -> same-area re-audit',
        '--max-rounds 0',
        'campaign_coverage.tsv',
        'boundary_and_input_contracts',
        'cross_area_regression_and_campaign_closure',
        'TELEGRAM_NOTIFY=0',
        'one final parent Telegram notification',
        'no providers',
        'no service lifecycle',
    ],
    'docs/automation/PROTECTED_AUTOMATION_FILES.md': [
        '.automation/lib/controller_hardening_v2.sh',
        '.automation/lib/telegram_notify.sh',
        'check_progress.sh',
        'watch_progress.sh',
        'open_log.sh',
        'run-paper-autopilot.sh',
        'run-bugfix-autopilot.sh',
    ],
    '.automation/README.md': [
        '.automation/lib/run_common.sh',
        '.automation/lib/controller_hardening_v2.sh',
        '.automation/lib/telegram_notify.sh',
        'run-autonomous-implementation.sh',
        'run-autonomous-bugfix.sh',
        'run-paper-autopilot.sh',
        'run-bugfix-autopilot.sh',
        'TELEGRAM_NOTIFY=0',
        'parent campaign-final Telegram',
        'complete `artifacts/` directory',
    ],
    'docs/repo_status_current.md': [
        'run_autonomous_implementation=standardized_safe_local_goal_complete',
        'run_autonomous_bugfix=standardized_standalone_audit',
        'run_bugfix_autopilot=standardized_parent_for_broad_audit_and_repair',
        'run_paper_evaluation=retained_fixture_evaluator_not_initial_router',
        'run_paper_autopilot=standardized_and_selected_for_post_implementation_runtime_convergence',
        'autopilot_child_telegram=disabled',
        'autopilot_parent_telegram=final_only',
        'standalone_controller_telegram=enabled_by_default',
    ],
}

FORBIDDEN = [
    'run-paper-evaluation-12h.sh',
    'stop-autonomous-run.sh',
    'scripts/stop-autonomous-run.sh',
]

FORBIDDEN_FRAGMENTS = {
    'zip_codebase.sh': ['*/runtime/*'],
    'start.sh': ['. scripts/load-node-runtime.sh', 'source "$HOME/.nvm/nvm.sh"', 'source "$NVM_DIR/nvm.sh"'],
    'run-autonomous-implementation.sh': [
        'scripts/load-node-runtime.sh',
        'source "$HOME/.nvm/nvm.sh"',
        'source "$NVM_DIR/nvm.sh"',
    ],
    'run-autonomous-bugfix.sh': [
        'scripts/load-node-runtime.sh',
        'source "$HOME/.nvm/nvm.sh"',
        'source "$NVM_DIR/nvm.sh"',
        'Find and fix bug-class issues',
    ],

    'run-bugfix-autopilot.sh': [
        'scripts/load-node-runtime.sh',
        'source "$HOME/.nvm/nvm.sh"',
        'source "$NVM_DIR/nvm.sh"',
        'run-paper-evaluation.sh',
        'run-paper-autopilot.sh',
        'bash ./start.sh',
        'bash ./stop.sh',
        'forever',
        'MongoDB',
    ],
    'run-paper-autopilot.sh': [
        'scripts/load-node-runtime.sh',
        'source "$HOME/.nvm/nvm.sh"',
        'source "$NVM_DIR/nvm.sh"',
        'bash ./start.sh',
        'bash ./stop.sh',
        'forever',
        'MongoDB',
    ],
    'run-paper-evaluation.sh': [
        'scripts/load-node-runtime.sh',
        'source "$HOME/.nvm/nvm.sh"',
        'source "$NVM_DIR/nvm.sh"',
        'run-autonomous-bugfix.sh --from-artifacts',
        'paper_shell_quote()',
        'PAPER_EVALUATION_UNSUPPORTED_FOR_THIS_REPO',
        'local rc\n  rc=$?',
    ],
    'automation.config.sh': [
        'mkdir -p artifacts/private-paper-mode',
        'run-paper-evaluation.sh remains out of scope',
    ],
    'commands/run-pinned-interface-smoke.sh': [
        'scripts/load-node-runtime.sh',
        'mkdir -p "$out_dir"',
    ],
}


def fail(message: str) -> None:
    print(f'ERROR: {message}', file=sys.stderr)
    raise SystemExit(1)


def read(rel: str) -> str:
    path = ROOT / rel
    if not path.is_file():
        fail(f'missing required file: {rel}')
    return path.read_text(encoding='utf-8')


def main() -> None:
    for rel in SHELL_FILES:
        result = subprocess.run(['bash', '-n', str(ROOT / rel)], cwd=ROOT, text=True, capture_output=True)
        if result.returncode != 0:
            fail(f'bash syntax failed for {rel}: {result.stderr.strip()}')

    for rel, fragments in REQUIRED_FRAGMENTS.items():
        text = read(rel)
        for fragment in fragments:
            if fragment not in text:
                fail(f'{rel} missing required marker: {fragment}')

    for rel, fragments in FORBIDDEN_FRAGMENTS.items():
        text = read(rel)
        for fragment in fragments:
            if fragment in text:
                fail(f'{rel} contains forbidden marker: {fragment}')

    for rel in FORBIDDEN:
        if (ROOT / rel).exists():
            fail(f'obsolete automation helper still present: {rel}')

    package = json.loads(read('package.json'))
    for script in ['zip:codebase', 'autonomous:check', 'autonomous:start', 'autonomous:bugfix', 'paper:evaluation', 'paper:autopilot', 'bugfix', 'bugfix:autopilot', 'automation:status']:
        if script not in package.get('scripts', {}):
            fail(f'package.json missing script: {script}')

    print('validate_autonomous_controller_contract: ok')


if __name__ == '__main__':
    main()
